package com.imock.mmall.entity;

import java.io.Serializable;
import java.util.Date;

public class Cart implements Serializable {
    /**
     *
     */
    private Integer id;

    /**
     *
     */
    private Integer userId;

    /**
     *商品id
     */
    private Integer productId;

    /**
     *数量
     */
    private Integer quantity;

    /**
     *是否选择,1=已勾选,0=未勾选
     */
    private Integer checked;

    /**
     *创建时间
     */
    private Date createTime;

    /**
     *更新时间
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mmall_cart
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     *
     */
    public Integer getId() {
        return id;
    }

    /**
     *
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     *
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     *
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     *商品id
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     *商品id
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     *数量
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     *数量
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     *是否选择,1=已勾选,0=未勾选
     */
    public Integer getChecked() {
        return checked;
    }

    /**
     *是否选择,1=已勾选,0=未勾选
     */
    public void setChecked(Integer checked) {
        this.checked = checked;
    }

    /**
     *创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     *创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     *更新时间
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     *更新时间
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_cart
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", productId=").append(productId);
        sb.append(", quantity=").append(quantity);
        sb.append(", checked=").append(checked);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}