package com.imock.mmall.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Order implements Serializable {
    /**
     *订单id
     */
    private Integer id;

    /**
     *订单号
     */
    private Long orderNo;

    /**
     *用户id
     */
    private Integer userId;

    /**
     *
     */
    private Integer shippingId;

    /**
     *实际付款金额,单位是元,保留两位小数
     */
    private BigDecimal payment;

    /**
     *支付类型,1-在线支付
     */
    private Integer paymentType;

    /**
     *运费,单位是元
     */
    private Integer postage;

    /**
     *订单状态:0-已取消-10-未付款，20-已付款，40-已发货，50-交易成功，60-交易关闭
     */
    private Integer status;

    /**
     *支付时间
     */
    private Date paymentTime;

    /**
     *发货时间
     */
    private Date sendTime;

    /**
     *交易完成时间
     */
    private Date endTime;

    /**
     *交易关闭时间
     */
    private Date closeTime;

    /**
     *创建时间
     */
    private Date createTime;

    /**
     *更新时间
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mmall_order
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     *订单id
     */
    public Integer getId() {
        return id;
    }

    /**
     *订单id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     *订单号
     */
    public Long getOrderNo() {
        return orderNo;
    }

    /**
     *订单号
     */
    public void setOrderNo(Long orderNo) {
        this.orderNo = orderNo;
    }

    /**
     *用户id
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     *用户id
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     *
     */
    public Integer getShippingId() {
        return shippingId;
    }

    /**
     *
     */
    public void setShippingId(Integer shippingId) {
        this.shippingId = shippingId;
    }

    /**
     *实际付款金额,单位是元,保留两位小数
     */
    public BigDecimal getPayment() {
        return payment;
    }

    /**
     *实际付款金额,单位是元,保留两位小数
     */
    public void setPayment(BigDecimal payment) {
        this.payment = payment;
    }

    /**
     *支付类型,1-在线支付
     */
    public Integer getPaymentType() {
        return paymentType;
    }

    /**
     *支付类型,1-在线支付
     */
    public void setPaymentType(Integer paymentType) {
        this.paymentType = paymentType;
    }

    /**
     *运费,单位是元
     */
    public Integer getPostage() {
        return postage;
    }

    /**
     *运费,单位是元
     */
    public void setPostage(Integer postage) {
        this.postage = postage;
    }

    /**
     *订单状态:0-已取消-10-未付款，20-已付款，40-已发货，50-交易成功，60-交易关闭
     */
    public Integer getStatus() {
        return status;
    }

    /**
     *订单状态:0-已取消-10-未付款，20-已付款，40-已发货，50-交易成功，60-交易关闭
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     *支付时间
     */
    public Date getPaymentTime() {
        return paymentTime;
    }

    /**
     *支付时间
     */
    public void setPaymentTime(Date paymentTime) {
        this.paymentTime = paymentTime;
    }

    /**
     *发货时间
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     *发货时间
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     *交易完成时间
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     *交易完成时间
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     *交易关闭时间
     */
    public Date getCloseTime() {
        return closeTime;
    }

    /**
     *交易关闭时间
     */
    public void setCloseTime(Date closeTime) {
        this.closeTime = closeTime;
    }

    /**
     *创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     *创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     *更新时间
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     *更新时间
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_order
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", orderNo=").append(orderNo);
        sb.append(", userId=").append(userId);
        sb.append(", shippingId=").append(shippingId);
        sb.append(", payment=").append(payment);
        sb.append(", paymentType=").append(paymentType);
        sb.append(", postage=").append(postage);
        sb.append(", status=").append(status);
        sb.append(", paymentTime=").append(paymentTime);
        sb.append(", sendTime=").append(sendTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", closeTime=").append(closeTime);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}