package com.imock.mmall.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class OrderItem implements Serializable {
    /**
     *订单子表id
     */
    private Integer id;

    /**
     *
     */
    private Integer userId;

    /**
     *
     */
    private Long orderNo;

    /**
     *商品id
     */
    private Integer productId;

    /**
     *商品名称
     */
    private String productName;

    /**
     *商品图片地址
     */
    private String productImage;

    /**
     *生成订单时的商品单价，单位是元,保留两位小数
     */
    private BigDecimal currentUnitPrice;

    /**
     *商品数量
     */
    private Integer quantity;

    /**
     *商品总价,单位是元,保留两位小数
     */
    private BigDecimal totalPrice;

    /**
     *
     */
    private Date createTime;

    /**
     *
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mmall_order_item
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     *订单子表id
     */
    public Integer getId() {
        return id;
    }

    /**
     *订单子表id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     *
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     *
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     *
     */
    public Long getOrderNo() {
        return orderNo;
    }

    /**
     *
     */
    public void setOrderNo(Long orderNo) {
        this.orderNo = orderNo;
    }

    /**
     *商品id
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     *商品id
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     *商品名称
     */
    public String getProductName() {
        return productName;
    }

    /**
     *商品名称
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     *商品图片地址
     */
    public String getProductImage() {
        return productImage;
    }

    /**
     *商品图片地址
     */
    public void setProductImage(String productImage) {
        this.productImage = productImage == null ? null : productImage.trim();
    }

    /**
     *生成订单时的商品单价，单位是元,保留两位小数
     */
    public BigDecimal getCurrentUnitPrice() {
        return currentUnitPrice;
    }

    /**
     *生成订单时的商品单价，单位是元,保留两位小数
     */
    public void setCurrentUnitPrice(BigDecimal currentUnitPrice) {
        this.currentUnitPrice = currentUnitPrice;
    }

    /**
     *商品数量
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     *商品数量
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     *商品总价,单位是元,保留两位小数
     */
    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    /**
     *商品总价,单位是元,保留两位小数
     */
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     *
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     *
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     *
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     *
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_order_item
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", orderNo=").append(orderNo);
        sb.append(", productId=").append(productId);
        sb.append(", productName=").append(productName);
        sb.append(", productImage=").append(productImage);
        sb.append(", currentUnitPrice=").append(currentUnitPrice);
        sb.append(", quantity=").append(quantity);
        sb.append(", totalPrice=").append(totalPrice);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}