package com.imock.mmall.entity;

import java.io.Serializable;
import java.util.Date;

public class PayInfo implements Serializable {
    /**
     *
     */
    private Integer id;

    /**
     *用户id
     */
    private Integer userId;

    /**
     *订单号
     */
    private Long orderNo;

    /**
     *支付平台:1-支付宝,2-微信
     */
    private Integer payPlatform;

    /**
     *支付宝支付流水号
     */
    private String platformNumber;

    /**
     *支付宝支付状态
     */
    private String platformStatus;

    /**
     *创建时间
     */
    private Date createTime;

    /**
     *更新时间
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mmall_pay_info
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     *
     */
    public Integer getId() {
        return id;
    }

    /**
     *
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     *用户id
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     *用户id
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     *订单号
     */
    public Long getOrderNo() {
        return orderNo;
    }

    /**
     *订单号
     */
    public void setOrderNo(Long orderNo) {
        this.orderNo = orderNo;
    }

    /**
     *支付平台:1-支付宝,2-微信
     */
    public Integer getPayPlatform() {
        return payPlatform;
    }

    /**
     *支付平台:1-支付宝,2-微信
     */
    public void setPayPlatform(Integer payPlatform) {
        this.payPlatform = payPlatform;
    }

    /**
     *支付宝支付流水号
     */
    public String getPlatformNumber() {
        return platformNumber;
    }

    /**
     *支付宝支付流水号
     */
    public void setPlatformNumber(String platformNumber) {
        this.platformNumber = platformNumber == null ? null : platformNumber.trim();
    }

    /**
     *支付宝支付状态
     */
    public String getPlatformStatus() {
        return platformStatus;
    }

    /**
     *支付宝支付状态
     */
    public void setPlatformStatus(String platformStatus) {
        this.platformStatus = platformStatus == null ? null : platformStatus.trim();
    }

    /**
     *创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     *创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     *更新时间
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     *更新时间
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_pay_info
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", orderNo=").append(orderNo);
        sb.append(", payPlatform=").append(payPlatform);
        sb.append(", platformNumber=").append(platformNumber);
        sb.append(", platformStatus=").append(platformStatus);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}