package com.imock.mmall.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Product implements Serializable {
    /**
     *商品id
     */
    private Integer id;

    /**
     *分类id,对应mmall_category表的主键
     */
    private Integer categoryId;

    /**
     *商品名称
     */
    private String name;

    /**
     *商品副标题
     */
    private String subtitle;

    /**
     *产品主图,url相对地址
     */
    private String mainImage;

    /**
     *价格,单位-元保留两位小数
     */
    private BigDecimal price;

    /**
     *库存数量
     */
    private Integer stock;

    /**
     *商品状态.1-在售 2-下架 3-删除
     */
    private Integer status;

    /**
     *创建时间
     */
    private Date createTime;

    /**
     *更新时间
     */
    private Date updateTime;

    /**
     *图片地址,json格式,扩展用
     */
    private String subImages;

    /**
     *商品详情
     */
    private String detail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mmall_product
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     *商品id
     */
    public Integer getId() {
        return id;
    }

    /**
     *商品id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     *分类id,对应mmall_category表的主键
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     *分类id,对应mmall_category表的主键
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     *商品名称
     */
    public String getName() {
        return name;
    }

    /**
     *商品名称
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     *商品副标题
     */
    public String getSubtitle() {
        return subtitle;
    }

    /**
     *商品副标题
     */
    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle == null ? null : subtitle.trim();
    }

    /**
     *产品主图,url相对地址
     */
    public String getMainImage() {
        return mainImage;
    }

    /**
     *产品主图,url相对地址
     */
    public void setMainImage(String mainImage) {
        this.mainImage = mainImage == null ? null : mainImage.trim();
    }

    /**
     *价格,单位-元保留两位小数
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     *价格,单位-元保留两位小数
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     *库存数量
     */
    public Integer getStock() {
        return stock;
    }

    /**
     *库存数量
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     *商品状态.1-在售 2-下架 3-删除
     */
    public Integer getStatus() {
        return status;
    }

    /**
     *商品状态.1-在售 2-下架 3-删除
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     *创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     *创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     *更新时间
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     *更新时间
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     *图片地址,json格式,扩展用
     */
    public String getSubImages() {
        return subImages;
    }

    /**
     *图片地址,json格式,扩展用
     */
    public void setSubImages(String subImages) {
        this.subImages = subImages == null ? null : subImages.trim();
    }

    /**
     *商品详情
     */
    public String getDetail() {
        return detail;
    }

    /**
     *商品详情
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_product
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", categoryId=").append(categoryId);
        sb.append(", name=").append(name);
        sb.append(", subtitle=").append(subtitle);
        sb.append(", mainImage=").append(mainImage);
        sb.append(", price=").append(price);
        sb.append(", stock=").append(stock);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", subImages=").append(subImages);
        sb.append(", detail=").append(detail);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}