package com.imock.mmall.entity;

import java.io.Serializable;
import java.util.Date;

public class Shipping implements Serializable {
    /**
     *
     */
    private Integer id;

    /**
     *用户id
     */
    private Integer userId;

    /**
     *收货姓名
     */
    private String receiverName;

    /**
     *收货固定电话
     */
    private String receiverPhone;

    /**
     *收货移动电话
     */
    private String receiverMobile;

    /**
     *省份
     */
    private String receiverProvince;

    /**
     *城市
     */
    private String receiverCity;

    /**
     *区/县
     */
    private String receiverDistrict;

    /**
     *详细地址
     */
    private String receiverAddress;

    /**
     *邮编
     */
    private String receiverZip;

    /**
     *
     */
    private Date createTime;

    /**
     *
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mmall_shipping
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     *
     */
    public Integer getId() {
        return id;
    }

    /**
     *
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     *用户id
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     *用户id
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     *收货姓名
     */
    public String getReceiverName() {
        return receiverName;
    }

    /**
     *收货姓名
     */
    public void setReceiverName(String receiverName) {
        this.receiverName = receiverName == null ? null : receiverName.trim();
    }

    /**
     *收货固定电话
     */
    public String getReceiverPhone() {
        return receiverPhone;
    }

    /**
     *收货固定电话
     */
    public void setReceiverPhone(String receiverPhone) {
        this.receiverPhone = receiverPhone == null ? null : receiverPhone.trim();
    }

    /**
     *收货移动电话
     */
    public String getReceiverMobile() {
        return receiverMobile;
    }

    /**
     *收货移动电话
     */
    public void setReceiverMobile(String receiverMobile) {
        this.receiverMobile = receiverMobile == null ? null : receiverMobile.trim();
    }

    /**
     *省份
     */
    public String getReceiverProvince() {
        return receiverProvince;
    }

    /**
     *省份
     */
    public void setReceiverProvince(String receiverProvince) {
        this.receiverProvince = receiverProvince == null ? null : receiverProvince.trim();
    }

    /**
     *城市
     */
    public String getReceiverCity() {
        return receiverCity;
    }

    /**
     *城市
     */
    public void setReceiverCity(String receiverCity) {
        this.receiverCity = receiverCity == null ? null : receiverCity.trim();
    }

    /**
     *区/县
     */
    public String getReceiverDistrict() {
        return receiverDistrict;
    }

    /**
     *区/县
     */
    public void setReceiverDistrict(String receiverDistrict) {
        this.receiverDistrict = receiverDistrict == null ? null : receiverDistrict.trim();
    }

    /**
     *详细地址
     */
    public String getReceiverAddress() {
        return receiverAddress;
    }

    /**
     *详细地址
     */
    public void setReceiverAddress(String receiverAddress) {
        this.receiverAddress = receiverAddress == null ? null : receiverAddress.trim();
    }

    /**
     *邮编
     */
    public String getReceiverZip() {
        return receiverZip;
    }

    /**
     *邮编
     */
    public void setReceiverZip(String receiverZip) {
        this.receiverZip = receiverZip == null ? null : receiverZip.trim();
    }

    /**
     *
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     *
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     *
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     *
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_shipping
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", receiverName=").append(receiverName);
        sb.append(", receiverPhone=").append(receiverPhone);
        sb.append(", receiverMobile=").append(receiverMobile);
        sb.append(", receiverProvince=").append(receiverProvince);
        sb.append(", receiverCity=").append(receiverCity);
        sb.append(", receiverDistrict=").append(receiverDistrict);
        sb.append(", receiverAddress=").append(receiverAddress);
        sb.append(", receiverZip=").append(receiverZip);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}