package com.imock.mmall.entity;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
    /**
     *用户表id
     */
    private Integer id;

    /**
     *用户名
     */
    private String username;

    /**
     *用户密码，MD5加密
     */
    private String password;

    /**
     *
     */
    private String email;

    /**
     *
     */
    private String phone;

    /**
     *找回密码问题
     */
    private String question;

    /**
     *找回密码答案
     */
    private String answer;

    /**
     *角色0-管理员,1-普通用户
     */
    private Integer role;

    /**
     *创建时间
     */
    private Date createTime;

    /**
     *最后一次更新时间
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mmall_user
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     *用户表id
     */
    public Integer getId() {
        return id;
    }

    /**
     *用户表id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     *用户名
     */
    public String getUsername() {
        return username;
    }

    /**
     *用户名
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     *用户密码，MD5加密
     */
    public String getPassword() {
        return password;
    }

    /**
     *用户密码，MD5加密
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     *
     */
    public String getEmail() {
        return email;
    }

    /**
     *
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     *
     */
    public String getPhone() {
        return phone;
    }

    /**
     *
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     *找回密码问题
     */
    public String getQuestion() {
        return question;
    }

    /**
     *找回密码问题
     */
    public void setQuestion(String question) {
        this.question = question == null ? null : question.trim();
    }

    /**
     *找回密码答案
     */
    public String getAnswer() {
        return answer;
    }

    /**
     *找回密码答案
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    /**
     *角色0-管理员,1-普通用户
     */
    public Integer getRole() {
        return role;
    }

    /**
     *角色0-管理员,1-普通用户
     */
    public void setRole(Integer role) {
        this.role = role;
    }

    /**
     *创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     *创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     *最后一次更新时间
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     *最后一次更新时间
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mmall_user
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", username=").append(username);
        sb.append(", password=").append(password);
        sb.append(", email=").append(email);
        sb.append(", phone=").append(phone);
        sb.append(", question=").append(question);
        sb.append(", answer=").append(answer);
        sb.append(", role=").append(role);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}